### ISSUE TITLE
What causes overlapping changes, and what to do about them?

### ISSUE THREAD

**Issue by magthe** [haskell/stylish-haskell#368]
I have a file that produces this when I try to run `stylish-haskell` on it:

```
❯ stylish-haskell -i src/Types.hs
stylish-haskell: Language.Haskell.Stylish.Editor.applyChanges: refusing to make overlapping changes on lines 22-22, 25-25, 28-28, 34-34, 34-34, 35-35, 38-38, 41-41, 41-41
CallStack (from HasCallStack):
  error, called at lib/Language/Haskell/Stylish/Editor.hs:47:28 in stylish-haskell-0.12.2.0-1CTWTTs0EM65zXXQ6XHr5l:Language.Haskell.Stylish.Editor
```

I can't seem to make any changes to the file that will make it acceptable to `stylish-haskell`.

**Comment by magthe** [comment]
It does work with the default configuration, but not with my modified config:

```
# stylish-haskell configuration file
# ==================================

# The stylish-haskell tool is mainly configured by specifying steps. These steps
# are a list, so they have an order, and one specific step may appear more than
# once (if needed). Each file is processed by these steps in the given order.
steps:
  - module_header:
      indent: 2
      sort: true
      separate_lists: true

  - records:
      equals: "indent 2"
      first_field: "indent 2"
      field_comment: 2
      deriving: 2
      via: "indent 2"
      sort_deriving: true
      break_enums: false
      break_single_constructors: true
      curried_context: false

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: none
      list_align: new_line
      pad_module_names: false
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: false
      ghc_lib_parser: true

  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 8

  - trailing_whitespace: {}

  - squash: {}

columns: 120

newline: native

cabal: true
```
