### ISSUE TITLE
Some `records` configs cause variant types to not line up 

### ISSUE THREAD

**Issue by tysonzero** [haskell/stylish-haskell#395]
With the following config:

```
  - records:
      equals: "same_line"
      first_field: "indent 4"
      field_comment: 2
      deriving: 4
      via: "same_line"
      break_enums: true
      break_single_constructors: false
      curried_context: false
```

This code:

```
data Foo
    = Bar Bar
    | Baz
    | Qux Qux
```

Becomes:

```
data Foo = Bar Bar
           | Baz
           | Qux Qux
```
