### ISSUE TITLE
unicode_syntax option only replaces the first -> on a line  

### ISSUE THREAD

**Issue by t1lde** [haskell/stylish-haskell#404]
With unicode_syntax enabled, only the first -> on a line is replaced. Running again will replace the next -> on the line, and so on.

Version
- stylish-haskell 0.13.0.0

.stylish-haskell.yaml

```yaml
steps:
  - unicode_syntax:
       add_language_pragma: false
  ```
Test.hs:
```haskell
x :: Int -> Int -> Int
x = undefined
```

running `stylish-haskell -i Test.hs` gives:

```haskell
x ∷ Int → Int -> Int
x = undefined
```

running again:

```haskell
x ∷ Int → Int → Int
x = undefined
```
