### ISSUE TITLE
Formatting only GADT with "indent 2" instead of "same_line"

### ISSUE THREAD

**Issue by 0xmycf** [haskell/stylish-haskell#446]
SH formats my GADTs instead of this:
```hs
data Foo a where
  SomeA :: String -> Foo ()
  SomeB :: Bool   -> Foo String
  SomeC :: String -> Foo ()
```
like this:

```hs
data Foo a where SomeA :: String -> Foo ()
                 SomeB :: Bool -> Foo String
                 SomeC :: String -> Foo ()
```

This is probably due to this setting
```yaml
  - records:
      equals: "same_line"
#   instead of 
#   equals: "indent 2"
```

Is there some way to distinguish between GADTs and normal records so I can keep the "same_line" option but format GADT with an indent?
