### ISSUE TITLE
Align of mutl_way_if incorrect

### ISSUE THREAD

**Issue by erikd** [haskell/stylish-haskell#477]
In my `.stylish-haskell.yaml` I have:
```
  # Never align the right hand side of some elements.
  - simple_align:
      cases: never
      top_level_patterns: never
      records: never
      multi_way_if: never
  - squash: {}
```
and I still get the following diff:
```
     st <- getFileStatus fp
     if
       | isRegularFile st -> pure (fp : files, dirs)
-      | isDirectory st -> pure (files, fp : dirs)
-      | otherwise -> pure (files, dirs)
+      | isDirectory st   -> pure (files, fp : dirs)
+      | otherwise        -> pure (files, dirs)
 ```
